### ISSUE TITLE
send notify_email without auth

### ISSUE THREAD

**Issue by Cas-pian** [Yelp/elastalert#1404]
The notify_email is used to send notification to the admin when there's some error occured in programme runnning, but I found there's no auth config, `smtp_auth_file` seems to be loaded only in rule. How to set login info for this notify_email?

**Comment by dbook-kkbrandt** [comment]
So... notify_email can't be used with any smtp service that requires authorization?

**Comment by nacesprin** [comment]
I think it send by using smtp_* configuration

**Comment by Cas-pian** [comment]
@nacesprin Thanks for you reply

**Comment by Qmando** [comment]
This is true, however, it should be fixed when https://github.com/Yelp/elastalert/pull/1834 is merged.

**Comment by rdepril** [comment]
Hi @Qmando 

If I'm not mistaken, this issue is still present, and #1834 was closed and never merged.

What happened, and can I do something to help getting this feature into master?
