### ISSUE TITLE
ES 5, Error running query: TransportError(400

### ISSUE THREAD

**Issue by martinohansen** [Yelp/elastalert#856]
Hi, im runing ES 5 and just installed elastalert branch Support es5 #820 
Im getting the following error on some of my rules, see below for error and rule.

`
INFO:elastalert:Ran name ms sql job error MAW from 2017-01-06 15:53 CET to 2017-01-06 16:08 CET: 0 query hits, 0 matches, 0 alerts sent
WARNING:elasticsearch:GET http://localhost:9200/name-*/_search?_source_include=%40timestamp%2C%2A&ignore_unavailable=true&scroll=30s&size=10000 [status:400 request:0.004s]
ERROR:root:Error running query: TransportError(400, {u'line': 1, u'root_cause': [{u'reason': u'no [query] registered for [query]', u'type': u'parsing_exception', u'line': 1, u'col': 208}], u'type': u'parsing_exception', u'reason': u'no [query] registered for [query]', u'col': 208})
`
```
name: name ms sql job error MAW
es_host: localhost
es_port: 9200
index: name-*
any: failed
type: any

filter:
- query:
    query_string:
      query: "task: *Job*"
```

Thanks in advance.

**Comment by Qmando** [comment]
You are definitely using support_es5 branch? This looks like a bug that was specifically fixed by https://github.com/Yelp/elastalert/pull/820/commits/bb09323ad893b22d17e0d7cb2aa50c52db18f80d. 

Can you use run``python -c "import elastalert.elastalert;print elastalert.elastalert.ElastAlerter.is_five"`` just to verify for me that you have that branch? It should output ``<unbound method ElastAlerter.is_five>``.

You can try changing the filter to
```
filter:
 - query_string:
      query: "task: *Job*"
```

**Comment by martinohansen** [comment]
It outputs as expected, chaningen the rule syntax solved the issue. Thanks. #

**Comment by martinohansen** [comment]
Running the binary `elastalert-test-rule` returns the same _TransportError_ is it ES 5 ready yet?

**Comment by TroelsL** [comment]
I have a similar issue. I deleted my elastalert index, but still get the following error running any rule:

    WARNING:elasticsearch:GET http://elasticsearch2:9200/elastalert_status/elastaler
    t/_search?size=1000 [status:400 request:0.000s]
    ERROR:root:Error finding recent pending alerts: TransportError(400, {u'failed_sh
    ards': [{u'node': u'P06M7-VqSfuHCnz77thsjA', u'index': u'elastalert_status', u'r
    eason': {u'index_uuid': u'oiXcAfswQsuz5Uq6GOaR6w', u'index': u'elastalert_status
    ', u'reason': u'No mapping found for [alert_time] in order to sort on', u'type':
     u'query_shard_exception'}, u'shard': 0}], u'root_cause': [{u'index_uuid': u'oiX
    cAfswQsuz5Uq6GOaR6w', u'index': u'elastalert_status', u'reason': u'No mapping fo
    und for [alert_time] in order to sort on', u'type': u'query_shard_exception'}],
    u'caused_by': {u'index_uuid': u'oiXcAfswQsuz5Uq6GOaR6w', u'index': u'elastalert_
    status', u'reason': u'No mapping found for [alert_time] in order to sort on', u'
    type': u'query_shard_exception'}, u'grouped': True, u'reason': u'all shards fail
    ed', u'phase': u'query', u'type': u'search_phase_execution_exception'}) {'sort':
     {'alert_time': {'order': 'asc'}}, 'query': {'bool': {'filter': {'range': {'aler
    t_time': {'to': '2017-02-01T08:45:08.579Z', 'from': '2017-01-30T08:45:08.579Z'}}
    }, 'must': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:fal
    se'}}}}}
    Traceback (most recent call last):
    File "C:\Python27\lib\site-packages\elastalert-0.1.4-py2.7.egg\elastalert\elas
    talert.py", line 1085, in find_recent_pending_alerts
    size=1000)
    File "C:\Python27\lib\site-packages\elasticsearch\client\utils.py", line 68, i
    n _wrapped
    return func(*args, params=params, **kwargs)
    File "C:\Python27\lib\site-packages\elasticsearch\client\__init__.py", line 49
    8, in search
    params=params, body=body)
    File "C:\Python27\lib\site-packages\elasticsearch\transport.py", line 301, in
    perform_request
    status, headers, data = connection.perform_request(method, url, params, body
    , ignore=ignore, timeout=timeout)
    File "C:\Python27\lib\site-packages\elasticsearch\connection\http_requests.py"
    , line 72, in perform_request
    self._raise_error(response.status_code, raw_data)
    File "C:\Python27\lib\site-packages\elasticsearch\connection\base.py", line 10
    2, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_me
    ssage, additional_info)
    RequestError: TransportError(400, {u'failed_shards': [{u'node': u'P06M7-VqSfuHCn
    z77thsjA', u'index': u'elastalert_status', u'reason': {u'index_uuid': u'oiXcAfsw
    Qsuz5Uq6GOaR6w', u'index': u'elastalert_status', u'reason': u'No mapping found f
    or [alert_time] in order to sort on', u'type': u'query_shard_exception'}, u'shar
    d': 0}], u'root_cause': [{u'index_uuid': u'oiXcAfswQsuz5Uq6GOaR6w', u'index': u'
    elastalert_status', u'reason': u'No mapping found for [alert_time] in order to s
    ort on', u'type': u'query_shard_exception'}], u'caused_by': {u'index_uuid': u'oi
    XcAfswQsuz5Uq6GOaR6w', u'index': u'elastalert_status', u'reason': u'No mapping f
    ound for [alert_time] in order to sort on', u'type': u'query_shard_exception'},
    u'grouped': True, u'reason': u'all shards failed', u'phase': u'query', u'type':
    u'search_phase_execution_exception'})

My rule:

    type: flatline
    index: logstash-*
    threshold: 1
    timeframe: 
        minutes: 10
    filter: 
        - query_string: "fields.messageTemplate: \"Received data with ContentLength: {HeaderContentLength}\""

**Comment by TroelsL** [comment]
Running create-index again, deleting the old one yields a new error:

Tried another rule:

`filter:
- query:
        query_string:
            query: "fields.messageTemplate = \"[{rowcount} rows at {storerate} rows/sec] Inserting external forecasts\""
- query:
    query_string:
      query: "fields.applicationName = \"ExternalForecastInserter\""`

Since it seems to be query related:

`WARNING:elasticsearch:GET http://elasticsearch2:9200/logstash-*/_search?_source_
include=%40timestamp%2C%2A&ignore_unavailable=true&scroll=30s&size=10000 [status
:400 request:0.000s]
ERROR:root:Error running query: TransportError(400, {u'line': 1, u'root_cause':
[{u'reason': u'no [query] registered for [query]', u'type': u'parsing_exception'
, u'line': 1, u'col': 202}], u'type': u'parsing_exception', u'reason': u'no [que
ry] registered for [query]', u'col': 202})`

Manually running the GET request works fine. I assume it has trouble parsing the results.

Output of GET elasticsearch2:9200/elastalert_status/_mapping

`{
  "elastalert_status": {
    "mappings": {
      "elastalert": {
        "properties": {
          "@timestamp": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "aggregate_id": {
            "type": "keyword"
          },
          "alert_time": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "match_body": {
            "type": "object",
            "enabled": false
          },
          "rule_name": {
            "type": "keyword"
          }
        }
      },
      "elastalert_status": {
        "properties": {
          "@timestamp": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "rule_name": {
            "type": "keyword"
          }
        }
      },
      "silence": {
        "properties": {
          "@timestamp": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "rule_name": {
            "type": "keyword"
          },
          "until": {
            "type": "date",
            "format": "dateOptionalTime"
          }
        }
      },
      "elastalert_error": {
        "properties": {
          "@timestamp": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "data": {
            "type": "object",
            "enabled": false
          },
          "message": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "traceback": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          }
        }
      },
      "past_elastalert": {
        "properties": {
          "@timestamp": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "aggregate_id": {
            "type": "keyword"
          },
          "match_body": {
            "type": "object",
            "enabled": false
          },
          "rule_name": {
            "type": "keyword"
          }
        }
      }
    }
  }
}`

**Comment by Qmando** [comment]
Are you on the most recent version? That looks like a bug fixed in 0.1.7.

You can fix it by doing
```
filter:
- query_string:
      query: "fields.messageTemplate = \"[{rowcount} rows at {storerate} rows/sec] Inserting external forecasts\""
- query_string:
      query: "fields.applicationName = \"ExternalForecastInserter\""`
```
instead

**Comment by TroelsL** [comment]
Changing the query fixes it.

Without changing, I can still see the issue on branch support_es5. I'm on commit: 
https://github.com/Yelp/elastalert/commit/8043a9ddac7ae4dac38546d1198a2798d1d7c2a0

Seeing as this commit had been merged to master, I also tried that with the same results.

**Comment by Qmando** [comment]
Ah, so there is a bug in that code. Thanks for reporting this and making me check :)
https://github.com/Yelp/elastalert/commit/348254c8195267b96094639c0992586260d7c4e0

**Comment by TroelsL** [comment]
Thank YOU for fixing this so I won't have to change 200+ alerting rules by hand :)

I will check this tomorrow when I'm at work (if I remember).

**Comment by TroelsL** [comment]
That resolved it, thank you very much.

I would close this issue, but I just realized I hijacked another one.
